import type { Brand, Category, Deal } from "./types";

export const DEALS: Deal[] = [
  {
    id: 1,
    influencer: "Alex Rivera",
    avatar: "👗",
    brand: "ZARA",
    category: "Fashion",
    title: "Summer lookbook — you need these pieces fr",
    code: "ALEX25",
    discount: "25% OFF",
    expiry: "2d 14h",
    link: "#",
    views: "142K",
    clicks: "8.2K",
    saves: "3.1K",
    emoji: "👗",
    gradient: "linear-gradient(135deg, #1a0533, #3d0066)",
    isNew: false,
    expiring: true,
  },
  {
    id: 2,
    influencer: "Marcus Chen",
    avatar: "💪",
    brand: "MyProtein",
    category: "Fitness",
    title: "This pre-workout changed my morning routine completely",
    code: "MARCUS40",
    discount: "40% OFF",
    expiry: "5d 6h",
    link: "#",
    views: "89K",
    clicks: "5.4K",
    saves: "2.8K",
    emoji: "💪",
    gradient: "linear-gradient(135deg, #001a0d, #003322)",
    isNew: true,
    expiring: false,
  },
  {
    id: 3,
    influencer: "Priya Shah",
    avatar: "✨",
    brand: "Sephora",
    category: "Beauty",
    title: "Skincare routine that cleared my skin in 30 days",
    code: "PRIYA15",
    discount: "15% OFF",
    expiry: "12d",
    link: "#",
    views: "210K",
    clicks: "14K",
    saves: "9.2K",
    emoji: "✨",
    gradient: "linear-gradient(135deg, #1a0020, #4d003a)",
    isNew: false,
    expiring: false,
  },
  {
    id: 4,
    influencer: "Jake Wu",
    avatar: "💻",
    brand: "Notion",
    category: "Tech",
    title: "The productivity stack I use to run my 7-figure biz",
    code: "JAKE50",
    discount: "50% OFF",
    expiry: "1d 3h",
    link: "#",
    views: "67K",
    clicks: "12K",
    saves: "5.5K",
    emoji: "💻",
    gradient: "linear-gradient(135deg, #00071a, #001433)",
    isNew: true,
    expiring: true,
  },
];

export const BRANDS: Brand[] = [
  { emoji: "👗", name: "ZARA", codes: 4 },
  { emoji: "💪", name: "MyProtein", codes: 7 },
  { emoji: "✨", name: "Sephora", codes: 12 },
  { emoji: "💻", name: "Notion", codes: 3 },
  { emoji: "🎮", name: "Razer", codes: 5 },
  { emoji: "🏃", name: "Nike", codes: 9 },
];

export const CATEGORIES: readonly ["All", ...Category[]] = [
  "All",
  "Fashion",
  "Fitness",
  "Beauty",
  "Tech",
  "Travel",
  "Food",
];

export const TRENDING_SEARCHES: string[] = [
  "Summer Sale",
  "Nike Promo",
  "Skincare",
  "Tech Deals",
  "Gym Supplements",
  "Travel Codes",
  "Food & Drink",
  "Gaming",
];

export const CLICK_PERFORMANCE: number[] = [
  30, 45, 28, 60, 42, 78, 55, 90, 67, 110, 88, 142,
];
